// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// CometScraper is an autogenerated mock type for the CometScraper type
type CometScraper struct {
	mock.Mock
}

// StartCrawling provides a mock function with given fields:
func (_m *CometScraper) StartCrawling() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

type mockConstructorTestingTNewCometScraper interface {
	mock.TestingT
	Cleanup(func())
}

// NewCometScraper creates a new instance of CometScraper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCometScraper(t mockConstructorTestingTNewCometScraper) *CometScraper {
	mock := &CometScraper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
