definitions:
  request.CreateCometScraperReq:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
info:
  contact: {}
  termsOfService: http://swagger.io/terms/
  title: Go Boilerplate
  version: 1.0.0
paths:
  /api/v1/comet:
    get:
      consumes:
        - application/json
      description: Fetch CometScraper
      produces:
        - application/json
      responses:
        "200":
          description: ""
      summary: Fetch CometScraper
      tags:
        - CometScrapers
    post:
      consumes:
        - application/json
      description: Create CometScraper
      parameters:
        - description: CometScraper to create
          in: body
          name: comet scraper
          required: true
          schema:
            $ref: '#/definitions/request.CreateCometScraperReq'
      produces:
        - application/json
      responses:
        "200":
          description: ""
      summary: Create CometScraper
      tags:
        - CometScrapers
  /api/v1/comet/{id}:
    delete:
      consumes:
        - application/json
      description: Delete CometScraper
      parameters:
        - description: comet scraper id
          in: path
          name: id
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: ""
      summary: Delete CometScraper
      tags:
        - CometScrapers
    get:
      consumes:
        - application/json
      description: Get CometScraper
      parameters:
        - description: comet scraper id
          in: path
          name: id
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: ""
      summary: Get CometScraper
      tags:
        - CometScrapers
swagger: "2.0"